/** @format */

export const countries = {
  "United States": {
    flags: "https://flagcdn.com/us.svg",
    capital: "Washington, D.C.",
    cities: [
      "New York",
      "Los Angeles",
      "Chicago",
      "Houston",
      "Phoenix",
      "Philadelphia",
      "San Antonio",
      "San Diego",
      "Dallas",
      "San Jose",
    ],

    population: "331 million",
    area: "9.834 million km²",
    region: "Americas",
    touristSpot: "Statue of Liberty",
    touristImage:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Statue_of_Liberty_%28cropped%29.jpg/800px-Statue_of_Liberty_%28cropped%29.jpg",
    coordinates: { lat: 37.0902, lng: -95.7129 },
    languages: ["English"],
  },
  France: {
    flags: "https://flagcdn.com/fr.svg",
    capital: "Paris",
    cities: [
      "Paris",
      "Lyon",
      "Marseille",
      "Toulouse",
      "Nice",
      "Nantes",
      "Strasbourg",
      "Montpellier",
      "Bordeaux",
      "Lille",
    ],

    population: "67 million",
    area: "551,695 km²",
    region: "Europe",
    touristSpot: "Eiffel Tower",
    touristImage:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Tour_Eiffel_Wikimedia_Commons.jpg/800px-Tour_Eiffel_Wikimedia_Commons.jpg",
    coordinates: { lat: 48.8566, lng: 2.3522 },
    languages: ["French"],
  },
  Italy: {
    flags: "https://flagcdn.com/it.svg",
    capital: "Rome",
    cities: [
      "Rome",
      "Milan",
      "Florence",
      "Venice",
      "Naples",
      "Turin",
      "Palermo",
      "Genoa",
      "Bologna",
      "Verona",
    ],

    population: "60 million",
    area: "301,340 km²",
    region: "Europe",
    touristSpot: "Colosseum",
    touristImage:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Colosseo_2021.jpg/800px-Colosseo_2021.jpg",
    coordinates: { lat: 41.9028, lng: 12.4964 },
    languages: ["Italian"],
  },
  Norway: {
    flags: "https://flagcdn.com/no.svg",
    capital: "Oslo",
    cities: [
      "Oslo",
      "Bergen",
      "Trondheim",
      "Stavanger",
      "Drammen",
      "Fredrikstad",
      "Kristiansand",
      "Sandnes",
      "Tromsø",
      "Ålesund",
    ],

    population: "5.4 million",
    area: "323,802 km²",
    region: "Europe",
    touristSpot: "Fjord of Norway",
    touristImage:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Norway_Fjord.jpg/800px-Norway_Fjord.jpg",
    coordinates: { lat: 60.472, lng: 8.4689 },
    languages: ["Norwegian"],
  },
  Sweden: {
    flags: "https://flagcdn.com/se.svg",
    capital: "Stockholm",
    cities: [
      "Stockholm",
      "Gothenburg",
      "Malmo",
      "Uppsala",
      "Västerås",
      "Örebro",
      "Linköping",
      "Helsingborg",
      "Jönköping",
      "Norrköping",
    ],

    population: "10.3 million",
    area: "450,295 km²",
    region: "Europe",
    touristSpot: "Vasa Museum",
    touristImage:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Vasa_Museum%2C_Stockholm_%2811416971982%29.jpg/800px-Vasa_Museum%2C_Stockholm_%2811416971982%29.jpg",
    coordinates: { lat: 60.1282, lng: 18.6435 },
    languages: ["Swedish"],
  },
  Germany: {
    flags: "https://flagcdn.com/de.svg",
    capital: "Berlin",
    cities: [
      "Berlin",
      "Munich",
      "Hamburg",
      "Frankfurt",
      "Stuttgart",
      "Düsseldorf",
      "Dortmund",
      "Essen",
      "Leipzig",
      "Bremen",
    ],

    population: "83 million",
    area: "357,022 km²",
    region: "Europe",
    touristSpot: "Brandenburg Gate",
    touristImage:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Brandenburg_Gate_at_night.jpg/800px-Brandenburg_Gate_at_night.jpg",
    coordinates: { lat: 51.1657, lng: 10.4515 },
    languages: ["German"],
  },
  Switzerland: {
    flags: "https://flagcdn.com/ch.svg",
    capital: "Bern",
    cities: [
      "Zurich",
      "Geneva",
      "Bern",
      "Basel",
      "Lausanne",
      "Winterthur",
      "Lucerne",
      "St. Gallen",
      "Lugano",
      "Biel",
    ],

    population: "8.5 million",
    area: "41,290 km²",
    region: "Europe",
    touristSpot: "Matterhorn",
    touristImage:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Matterhorn%2C_Val_Tournenche%2C_Italy_-_by_R_M_A.jpg/800px-Matterhorn%2C_Val_Tournenche%2C_Italy_-_by_R_M_A.jpg",
    coordinates: { lat: 46.8182, lng: 8.2275 },
    languages: ["German", "French", "Italian"],
  },
  England: {
    flags: "https://flagcdn.com/gb-eng.svg",
    capital: "London",
    cities: [
      "London",
      "Manchester",
      "Birmingham",
      "Liverpool",
      "Leeds",
      "Sheffield",
      "Bristol",
      "Newcastle",
      "Nottingham",
      "Leicester",
    ],

    population: "56 million",
    area: "130,395 km²",
    region: "Europe",
    touristSpot: "Big Ben",
    touristImage:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Big_Ben%2C_London%2C_England_%28cropped%29.jpg/800px-Big_Ben%2C_London%2C_England_%28cropped%29.jpg",
    coordinates: { lat: 51.509865, lng: -0.118092 },
    languages: ["English"],
  },
  Canada: {
    flags: "https://flagcdn.com/ca.svg",
    capital: "Ottawa",
    cities: [
      "Toronto",
      "Vancouver",
      "Montreal",
      "Calgary",
      "Ottawa",
      "Edmonton",
      "Winnipeg",
      "Quebec City",
      "Hamilton",
      "Kitchener",
    ],

    population: "38 million",
    area: "9.985 million km²",
    region: "Americas",
    touristSpot: "CN Tower",
    touristImage:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/CN_Tower_%28cropped%29.jpg/800px-CN_Tower_%28cropped%29.jpg",
    coordinates: { lat: 56.1304, lng: -106.3468 },
    languages: ["English", "French"],
  },
  China: {
    flags: "https://flagcdn.com/cn.svg",
    capital: "Beijing",
    cities: [
      "Beijing",
      "Shanghai",
      "Guangzhou",
      "Shenzhen",
      "Chengdu",
      "Wuhan",
      "Chongqing",
      "Tianjin",
      "Xi'an",
      "Hangzhou",
    ],

    population: "1.4 billion",
    area: "9.597 million km²",
    region: "Asia",
    touristSpot: "Great Wall of China",
    touristImage:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Great_Wall_of_China_%28cropped%29.jpg/800px-Great_Wall_of_China_%28cropped%29.jpg",
    coordinates: { lat: 35.8617, lng: 104.1954 },
    languages: ["Mandarin"],
  },
  "South Korea": {
    flags: "https://flagcdn.com/kr.svg",
    capital: "Seoul",
    cities: [
      "Seoul",
      "Busan",
      "Incheon",
      "Daegu",
      "Daejeon",
      "Gwangju",
      "Suwon",
      "Ulsan",
      "Changwon",
      "Yongin",
    ],

    population: "51 million",
    area: "100,210 km²",
    region: "Asia",
    touristSpot: "Gyeongbokgung Palace",
    touristImage:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Gyeongbokgung%2C_Seoul_%2819455256857%29.jpg/800px-Gyeongbokgung%2C_Seoul_%2819455256857%29.jpg",
    coordinates: { lat: 35.9078, lng: 127.7669 },
    languages: ["Korean"],
  },
  Japan: {
    flags: "https://flagcdn.com/jp.svg",
    capital: "Tokyo",
    cities: [
      "Tokyo",
      "Osaka",
      "Kyoto",
      "Yokohama",
      "Nagoya",
      "Sapporo",
      "Kobe",
      "Fukuoka",
      "Hiroshima",
      "Sendai",
    ],

    population: "126 million",
    area: "377,975 km²",
    region: "Asia",
    touristSpot: "Mount Fuji",
    touristImage:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Mount_Fuji_%28cropped%29.jpg/800px-Mount_Fuji_%28cropped%29.jpg",
    coordinates: { lat: 36.2048, lng: 138.2529 },
    languages: ["Japanese"],
  },
  India: {
    flags: "https://flagcdn.com/in.svg",
    capital: "New Delhi",
    cities: [
      "Mumbai",
      "Delhi",
      "Bangalore",
      "Hyderabad",
      "Chennai",
      "Kolkata",
      "Ahmedabad",
      "Pune",
      "Jaipur",
      "Lucknow",
    ],

    population: "1.366 billion",
    area: "3.287 million km²",
    region: "Asia",
    touristSpot: "Taj Mahal",
    touristImage:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Taj_Mahal_%28cropped%29.jpg/800px-Taj_Mahal_%28cropped%29.jpg",
    coordinates: { lat: 20.5937, lng: 78.9629 },
    languages: ["Hindi"],
  },
  Nepal: {
    flags: "https://flagcdn.com/np.svg",
    capital: "Kathmandu",
    cities: [
      "Kathmandu",
      "Pokhara",
      "Lalitpur",
      "Biratnagar",
      "Bharatpur",
      "Janakpur",
      "Hetauda",
      "Dharan",
      "Bhaktapur",
      "Butwal",
    ],

    population: "30 million",
    area: "147,516 km²",
    region: "Asia",
    touristSpot: "Mount Everest",
    touristImage:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Mount_Everest_%28cropped%29.jpg/800px-Mount_Everest_%28cropped%29.jpg",
    coordinates: { lat: 28.3949, lng: 84.124 },
    languages: ["Nepali"],
  },
  Vietnam: {
    flags: "https://flagcdn.com/vn.svg",
    capital: "Hanoi",
    cities: [
      "Hanoi",
      "Ho Chi Minh City",
      "Da Nang",
      "Haiphong",
      "Can Tho",
      "Bien Hoa",
      "Nha Trang",
      "Buon Ma Thuot",
      "Hue",
      "Vung Tau",
    ],

    population: "97 million",
    area: "331,210 km²",
    region: "Asia",
    touristSpot: "Halong Bay",
    touristImage:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Halong_Bay_%28cropped%29.jpg/800px-Halong_Bay_%28cropped%29.jpg",
    coordinates: { lat: 14.0583, lng: 108.2772 },
    languages: ["Vietnamese"],
  },
  Thailand: {
    flags: "https://flagcdn.com/th.svg",
    capital: "Bangkok",
    cities: [
      "Bangkok",
      "Chiang Mai",
      "Phuket",
      "Pattaya",
      "Hat Yai",
      "Udon Thani",
      "Chiang Rai",
      "Nakhon Ratchasima",
      "Surat Thani",
      "Khon Kaen",
    ],

    population: "69 million",
    area: "513,120 km²",
    region: "Asia",
    touristSpot: "Grand Palace",
    touristImage:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Grand_Palace_Bangkok_%28cropped%29.jpg/800px-Grand_Palace_Bangkok_%28cropped%29.jpg",
    coordinates: { lat: 15.87, lng: 100.9925 },
    languages: ["Thai"],
  },
  Greece: {
    flags: "https://flagcdn.com/gr.svg",
    capital: "Athens",
    cities: [
      "Athens",
      "Thessaloniki",
      "Patras",
      "Heraklion",
      "Larissa",
      "Volos",
      "Ioannina",
      "Chania",
      "Kalamata",
      "Rhodes",
    ],

    population: "10.4 million",
    area: "131,957 km²",
    region: "Europe",
    touristSpot: "Acropolis of Athens",
    touristImage:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Acropolis_of_Athens_%28cropped%29.jpg/800px-Acropolis_of_Athens_%28cropped%29.jpg",
    coordinates: { lat: 37.9838, lng: 23.7275 },
    languages: ["Greek"],
  },
};

export const countries_list = Object.keys(countries).map((country) => {
  return {
    name: country,
    ...countries[country],
  };
});
