import { Roboto } from "next/font/google";
import "./globals.css";

//components
import Footer from "../components/footer";
import Header from "@/components/Header";

const roboto = Roboto({ 
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: '--font-roboto', 
});

export const metadata = {
  title: "Hackathon24",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
